server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: calculator
          uri: http://localhost:8080
          predicates:
            - Path=/add/**,/subtract/**,/multiply/**
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/todos/**